const appData = [
    {question: "What type of farm does Dwight own?",
    answers: ["Beet", "Potato", "Sweet Corn", "Soybean"],
    rightAnswer: "Beet",
    rightImage: "right-beets.jpg",
    rightAlt: "Dwight and Mose on their beet farm.",
    wrongImage: "wrong-andy-bloody.jpg",
    wrongAlt: "Andy running a 5k with bloddy nipples."},
    {question: "Which of Angela’s cats does Dwight mercy-kill in the freezer?",
    answers: ["Bandit", "Garbage", "Sprinkles", "Princess Lady"],
    rightAnswer: "Sprinkles",
    rightImage: "right-sprinkles.jpg",
    rightAlt: "Picture of Dwight with meme about curiosity killing the cat and stuffing it in the freezer.",
    wrongImage: "wrong-andy-hits-dwight.jpg",
    wrongAlt: "Andy slowly hitting Dwight with his Prius."},
    {question: "What acapella group was Andy in during his time at Cornell?",
    answers: ["CresenDudes", "Here Comes Treble", "Chord of the Rings", "Pitch Slapped"],
    rightAnswer: "Here Comes Treble",
    rightImage: "right-treble.png",
    rightAlt: "Picture of 'Here Comes Treble' including Broccoli Rob.",
    wrongImage: "wrong-andy-poop-on-car.png",
    wrongAlt: "Andy pooping on the hood of Charles's car."},
    {question: "Who does Michael hit with his car?",
    answers: ["Phyllis", "Stanley", "Pepperoni Tony", "Meredith"],
    rightAnswer: "Meredith",
    rightImage: "right-meredith-car.jpg",
    rightAlt: "Meredith rolling up on the hood of Michael's car after he hits her in the parking lot.",
    wrongImage: "wrong-car-in-lake.jpg",
    wrongAlt: "Michael driving his car into the lake because that's what the GPS said to do."},
    {question: "At a dinner party, Michael describes the wine as having:",
    answers: ["a hint of Sunny-D", "an oaky afterbirth", "stewed prune origins", "one too many coolers"],
    rightAnswer: "an oaky afterbirth",
    rightImage: "right-afterbirth.jpg",
    rightAlt: "Michael and Jan sipping wine at the dinner party.",
    wrongImage: "wrong-dwight-liar.png",
    wrongAlt: "Dwight standing on a desk with a 'liar' sign around his neck as punishment."},
    {question: "Why does Kevin get fired?",
    answers: ["Making jokes that were offensive about the mentally disabled", "Missing too many days of work", "Making up fake numbers to balance the books", "Sexual harassment"],
    rightAnswer: "Making up fake numbers to balance the books",
    rightImage: "right-kevin-fired.jpg",
    rightAlt: "Kevin holding his 'your fired' cake.",
    wrongImage: "wrong-kevin-broccoli.jpg",
    wrongAlt: "Michael trying to force Kevin to eat broccoli."},
    {question: "Who was Jan’s young assistant?",
    answers: ["Carter", "Hunter", "Colton", "Tanner"],
    rightAnswer: "Hunter",
    rightImage: "right-hunter.jpg",
    rightAlt: "Jan enjoying Hunter's music.",
    wrongImage: "wrong-kevin-chili.jpg",
    wrongAlt: "Kevin about to drop his vat of chili on the office floor."},
    {question: "What company buys Dunder Mifflin when bankruptcy is imminent?",
    answers: ["Sabre", "Super Printer", "Sultan", "Samsonite"],
    rightAnswer: "Sabre",
    rightImage: "right-sabre.jpg",
    rightAlt: "Jim sign spinning for Sabre.",
    wrongImage: "wrong-meredith-shaved-head.jpg",
    wrongAlt: "Meredith shaving her head."},
    {question: "Where do Jim and Pam get married?",
    answers: ["Times Square NYC", "Schrute Farms", "At the Scranton office", "Niagara Falls"],
    rightAnswer: "Niagara Falls",
    rightImage: "right-niagara.jpg",
    rightAlt: "Jim and Pam getting married on a boat at Niagara Falls.",
    wrongImage: "wrong-michael-disappointed.jpg",
    wrongAlt: "Michael looking distressed and disappointed."},
    {question: "According to Prison Mike, what’s the worst thing about prison?",
    answers: ["The dementors", "The food", "The arts and crafts", "The weight room"],
    rightAnswer: "The dementors",
    rightImage: "right-dementors.jpg",
    rightAlt: "Dementors hovering around Hogwarts in Harry Potter.",
    wrongImage: "wrong-toby-hospital.jpg",
    wrongAlt: "Toby in the hospital with a neck immobilization device."}
];

const characterResult = [
    {character: "Kevin",
    characterText: "You really Kevin'ed this one. Why don't you move your things into the annex.",
    characterImage: "kevinmalone.jpg",
    characterAlt: "Kevin Malone looking sideways."},
    {character: "Kevin",
    characterText: "You really Kevin'ed this one. Why don't you move your things into the annex.",
    characterImage: "kevinmalone.jpg",
    characterAlt: "Kevin Malone looking sideways."},
    {character: "Devon",
    characterText: "He was fired in Season 2. Enough said.",
    characterImage: "devonwhite.jpg",
    characterAlt: "Devon White in a hobo costume."},
    {character: "Devon",
    characterText: "He was fired in Season 2. Enough said.",
    characterImage: "devonwhite.jpg",
    characterAlt: "Devon White in a hobo costume."},
    {character: "Andy",
    characterText: "You've got some work to do, but you might just be good enough to fake your way into being in charge!",
    characterImage: "andybernard.jpg",
    characterAlt: "Andy Bernard sitting at his desk with his hands in the air."},
    {character: "Andy",
    characterText: "You've got some work to do, but you might just be good enough to fake your way into being in charge!",
    characterImage: "andybernard.jpg",
    characterAlt: "Andy Bernard sitting at his desk with his hands in the air."},
    {character: "Jim & Pam",
    characterText: "You did well enough to capture hearts, and you probably had a good time while you did it!",
    characterImage: "jimandpam.jpg",
    characterAlt: "Jim and Pam in the conference room. Pam is smiling. Jim is smirking."},
    {character: "Jim & Pam",
    characterText: "You did well enough to capture hearts, and you probably had a good time while you did it!",
    characterImage: "jimandpam.jpg",
    characterAlt: "Jim and Pam in the conference room. Pam is smiling. Jim is smirking."},
    {character: "Dwight",
    characterText: "Well done! You've got 'Assistant to the Regional Manager' written all over you!",
    characterImage: "dwightschrute.jpg",
    alt: "Headshot of Dwight Schrute."},
    {character: "Dwight",
    characterText: "Well done! You've got 'Assistant to the Regional Manager' written all over you!",
    characterImage: "dwightschrute.jpg",
    characterAlt: "Headshot of Dwight Schrute."},
    {character: "Michael",
    characterText: "You embody all that is pure and good about the Scranton branch of Dunder Mifflin!",
    characterImage: "michaelscott.jpg",
    characterAlt: "Michael Scott smiling at his desk."}
];